# Generated by Django 4.0.2 on 2022-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_plinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plinks',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
